###
GET http://localhost:8081/bookstore/managers/purchases
Member-Id: 1


###
POST http://localhost:8081/bookstore/members/purchases
Content-Type: application/json
Member-Id: 3

{

  "deliveryPrice" : 100,
  "totalPrice": 100000,
  "road": "광주",
  "password": "1234",
  "orderId" : "b5a79f5b-faaf-4de0-897c-e0c0101a1c22"
}

###
PUT http://localhost:8081/bookstore/managers/purchases/b5a79f5b-faaf-4de0-897c-e0c0101a1c11?purchaseStatus=CONFIRMED
Content-Type: application/json
Member-Id: 1


###
PUT http://localhost:8081/bookstore/members/purchases/4
Content-Type: application/json
Member-Id: 1

{
  "purchaseStatus": "COMPLETED"
}

###
POST http://localhost:8081/bookstore/guests/purchases
Content-Type: application/json

{
  "deliveryPrice": 1000,
  "orderId": "123e4567-e89b-12d3-a456-426614174000",
  "password": "1234",
  "totalPrice": 100000,
  "road": "동탄"
}

###
PUT http://localhost:8081/bookstore/guests/purchases
Content-Type: application/json
Member-Id: 1

{
  "purchaseStatus": "COMPLETED",
  "orderNumber": "fa1e07cc-aa1f-4ebf-8752-0c564f2cd90c",
  "password": "1234"
}



##################

POST http://localhost:8081/bookstore/purchases/books
Content-Type: application/json
Member-Id: 3

{
  "bookId": 21,
  "quantity": 5,
  "price":  100,
  "purchaseId": 26
}

###
GET http://localhost:8081/bookstore/purchases/books/4?page=0&size=5
Member-Id: 1

###
GET http://localhost:8081/bookstore/members/purchases?page=0&size=3
Member-Id: 1